/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-23 12:59:42 
*/
export interface IdarkTheme {
    body: "#363537";
    text: "#FAFAFA";
    toggleBorder: "#6B8096";
    gradient: "linear-gradient(#091236, #1E215D)";
}
